# Generated by Django 3.0.2 on 2020-01-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_pub',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
